// registry/svelte/v2/cell/TextCell.svelte
<script lang="ts">
  import type { TextCellProps } from "structured-table";

  let { data }: { data: TextCellProps } = $props();
</script>

<p>
  {#if Array.isArray(data.value)}
    {#each data.value as node (node.uid)}
      {#if node.type === "string"}{node.data}{/if}{#if node.type === "html" && node.tag === "br"}<br />{/if}
    {/each}
  {:else}
    {data.value}
  {/if}
</p>

// registry/vue/v2/cell/TextCell.vue
<script setup lang="ts">
import { TextCellProps } from "structured-table";

defineProps<{
  data: TextCellProps;
}>();
</script>

<template>
  <p>
    <template v-if="Array.isArray(data.value)">
      <template v-for="node in data.value" :key="node.uid">
        <template v-if="node.type === 'string'">{{ node.data }}</template>
        <br v-else-if="node.type === 'html' && node.tag === 'br'" />
      </template>
    </template>
    <template v-else>{{ data.value }}</template>
  </p>
</template>
