// apps/web/src/components/stl-render-react/latest/cell/TextCell.tsx
import React from "react";
import { TextCellProps } from "structured-table";

const TextCell = React.memo(({ data }: { data: TextCellProps }) => {
    if (!Array.isArray(data.value)) {
        return <p>{data.value}</p>;
    }
    return (
        <p>
            {data.value.map((node) => {
                if (node.type === "string") return <React.Fragment key={node.uid}>{node.data}</React.Fragment>;
                if (node.type === "html" && node.tag === "br") return <br key={node.uid} />;
                return null;
            })}
        </p>
    );
});
TextCell.displayName = "TextCell";

export { TextCell };

// registry/vue/v2/cell/TextCell.vue
<script setup lang="ts">
import { TextCellProps } from "structured-table";

defineProps<{
  data: TextCellProps;
}>();
</script>

<template>
  <p>
    <template v-if="Array.isArray(data.value)">
      <template v-for="node in data.value" :key="node.uid">
        <template v-if="node.type === 'string'">{{ node.data }}</template>
        <br v-else-if="node.type === 'html' && node.tag === 'br'" />
      </template>
    </template>
    <template v-else>{{ data.value }}</template>
  </p>
</template>
