// registry/svelte/v2/table/TableView.svelte
<script lang="ts">
  import type { SanityTable } from "structured-table";
  import TextCell from "../cell/TextCell.svelte";
  import LinkCell from "../cell/LinkCell.svelte";
  import ButtonCell from "../cell/ButtonCell.svelte";
  import "../style.css";

  let {
    data,
    className = "border",
  }: { data: SanityTable; className?: string } = $props();
</script>

<div class={`st-theme-${className}`}>
  <table>
    {#if data.header}
      <thead>
        <tr>
          {#if data.showSerialIndex}<th>#</th>{/if}
          {#each data.header.cells as cell (cell.uid)}
            <th
              colspan={cell.colSpan ?? 1}
              rowspan={cell.rowSpan ?? 1}
              style:text-align={cell.align ?? "left"}
              class={cell.class}
            >
              {#if cell.type === "text"}<TextCell data={cell} />
              {:else if cell.type === "link"}<LinkCell data={cell} />
              {:else if cell.type === "button"}<ButtonCell data={cell} />
              {/if}
            </th>
          {/each}
        </tr>
      </thead>
    {/if}

    <tbody>
      {#each data.body as row, idx (row.uid)}
        <tr>
          {#if data.showSerialIndex}<td>{idx + 1}</td>{/if}
          {#each row.cells as cell (cell.uid)}
            <svelte:element
              this={cell.cellType === "header" ? "th" : "td"}
              colspan={cell.colSpan ?? 1}
              rowspan={cell.rowSpan ?? 1}
              style:text-align={cell.align ?? "left"}
              class={cell.class}
            >
              {#if cell.type === "text"}<TextCell data={cell} />
              {:else if cell.type === "link"}<LinkCell data={cell} />
              {:else if cell.type === "button"}<ButtonCell data={cell} />
              {/if}
            </svelte:element>
          {/each}
        </tr>
      {/each}
    </tbody>

    {#if data.footer && data.footer.cells.length > 0}
      <tfoot>
        <tr>
          {#if data.showSerialIndex}<th>#</th>{/if}
          {#each data.footer.cells as cell (cell.uid)}
            <th
              colspan={cell.colSpan ?? 1}
              rowspan={cell.rowSpan ?? 1}
              style:text-align={cell.align ?? "left"}
              class={cell.class}
            >
              {#if cell.type === "text"}<TextCell data={cell} />
              {:else if cell.type === "link"}<LinkCell data={cell} />
              {:else if cell.type === "button"}<ButtonCell data={cell} />
              {/if}
            </th>
          {/each}
        </tr>
      </tfoot>
    {/if}
  </table>
</div>

// registry/vue/v2/table/TableView.vue
<script setup lang="ts">
import { SanityTable, TableCell } from "structured-table";
import { ButtonCell, LinkCell, TextCell } from "../cell";
import "../style.css";

interface Props {
  data: SanityTable;
  className?: string;
}

withDefaults(defineProps<Props>(), {
  className: "border",
});

const getComponent = (type: TableCell["type"]) => {
  switch (type) {
    case "text":
      return TextCell;
    case "link":
      return LinkCell;
    case "button":
      return ButtonCell;
    default:
      return null;
  }
};
</script>

<template>
  <div :class="`st-theme-${className}`">
    <table>
      <thead v-if="data.header">
        <tr>
          <th v-if="data.showSerialIndex">#</th>
          <th
            v-for="dh in data.header.cells"
            :key="dh.uid"
            :colSpan="dh.colSpan ?? 1"
            :rowSpan="dh.rowSpan ?? 1"
            :style="{ textAlign: dh.align || 'left' }"
            :class="dh.class"
          >
            <component :is="getComponent(dh.type)" :data="dh" />
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, idx) in data.body" :key="row.uid">
          <td v-if="data.showSerialIndex">{{ idx + 1 }}</td>
          <component
            v-for="cell in row.cells"
            :key="cell.uid"
            :is="cell.cellType === 'header' ? 'th' : 'td'"
            :colSpan="cell.colSpan ?? 1"
            :rowSpan="cell.rowSpan ?? 1"
            :style="{ textAlign: cell.align || 'left' }"
            :class="cell.class"
          >
            <component :is="getComponent(cell.type)" :data="cell" />
          </component>
        </tr>
      </tbody>
      <tfoot v-if="data.footer && data.footer.cells.length > 0">
        <tr>
          <th v-if="data.showSerialIndex">#</th>
          <th
            v-for="df in data.footer.cells"
            :key="df.uid"
            :colSpan="df.colSpan ?? 1"
            :rowSpan="df.rowSpan ?? 1"
            :style="{ textAlign: df.align || 'left' }"
            :class="df.class"
          >
            <component :is="getComponent(df.type)" :data="df" />
          </th>
        </tr>
      </tfoot>
    </table>
  </div>
</template>
